import { describe, expect, it } from "vitest";
import { questionGenerationPrompt, selectReviewPlan, type ReviewCandidate, type ReviewHistory } from "../src/review.js";
const item = (id: number, kind: "due"|"fresh" = "due"): ReviewCandidate => ({ kind,key:`item:${id}`,learningItemId:`item-${id}`,mistakeCategory:null,text:`expression ${id}`,meaning:"meaning",example:"example",importance:id%3===0?"high":"medium",overdueDays:20-id });
const mistake: ReviewCandidate = {kind:"mistake",key:"mistake:articles",learningItemId:null,mistakeCategory:"articles",text:"articles",evidence:[{original:"I went to office",corrected:"I went to the office"}]};
const focus: ReviewCandidate = {kind:"focus",key:"focus:past",learningItemId:null,mistakeCategory:"other",text:"Tell past-tense stories consistently"};
describe("Telegram review selection", () => {
  it("uses the intended mix and creates a constrained generation prompt", () => { const plan=selectReviewPlan({due:[item(1),item(2),item(3)],fresh:[item(4,"fresh")],mistakes:[mistake],focus,count:5,history:[]}); expect(plan.map(x=>x.kind)).toEqual(["due","due","mistake","fresh","focus"]); const prompt=questionGenerationPrompt(plan); expect(prompt).toContain('"expectedAnswer"'); expect(prompt).toContain("Never use TOEIC"); });
  it("simulates two weeks without repeating an item and question-type pair", () => { let history:ReviewHistory[]=[]; const seen=new Set<string>(); for(let day=0;day<14;day++){ const now=new Date(Date.UTC(2026,7,1+day)); const plan=selectReviewPlan({due:Array.from({length:10},(_,i)=>item(i+1)),fresh:[item(11,"fresh"),item(12,"fresh")],mistakes:[mistake],focus,count:4,history,now}); expect(plan).toHaveLength(4); for(const q of plan){ const id=q.learningItemId??`mistake:${q.mistakeCategory}`; const key=`${id}:${q.questionType}`; expect(seen.has(key)).toBe(false); seen.add(key); history.push({learning_item_id:q.learningItemId,mistake_category:q.mistakeCategory,question_type:q.questionType,created_at:now.toISOString()}); } } expect(seen.size).toBe(56); });
  it("degrades gracefully when a preferred pool is empty", () => { const plan=selectReviewPlan({due:[item(1),item(2),item(3)],fresh:[item(4,"fresh")],mistakes:[],focus:null,count:4,history:[]}); expect(plan).toHaveLength(4); expect(plan.every(q=>q.learningItemId)).toBe(true); });
});
