import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { EmptyState } from "../components/EmptyState";
import { LoadingSkeleton } from "../components/LoadingSkeleton";
import { MasteryDots } from "../components/MasteryDots";
import { loadLearningItem, type LearningItemDetail } from "../lib/items";

const label = (value: string) => value.replace(/_/g, " ");
const date = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));

export function LearningItemDetailPage() {
  const { id = "" } = useParams();
  const [item, setItem] = useState<LearningItemDetail | null | undefined>();
  const [error, setError] = useState("");
  useEffect(() => { let active = true; void loadLearningItem(id).then((row) => active && setItem(row)).catch(() => active && setError("We couldn’t load this learning item.")); return () => { active = false; }; }, [id]);
  if (error) return <EmptyState icon="↻" title="Item couldn’t load" description={error}/>;
  if (item === undefined) return <LoadingSkeleton/>;
  if (item === null) return <EmptyState title="Item not found" description="It may have been archived or belongs to another account."/>;

  return <div className="space-y-4"><header><Link to="/items" className="text-sm font-semibold text-emerald-700 hover:underline dark:text-mint">← Learning items</Link><div className="mt-6 flex flex-wrap items-center gap-3"><span className="rounded-full bg-mint/50 px-3 py-1 text-xs font-bold uppercase tracking-wider text-emerald-900 dark:bg-mint dark:text-ink">{label(item.type)}</span><span className="text-xs font-semibold capitalize text-slate-500">{item.status}</span></div><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">{item.text}</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{item.meaning}</p></header>
    <section className="grid gap-4 lg:grid-cols-[1fr_18rem]"><article className="rounded-[1.5rem] border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Example</p><blockquote className="mt-4 border-l-4 border-mint pl-4 text-xl font-medium leading-8">{item.example}</blockquote>{item.note && <p className="mt-5 rounded-xl bg-mist p-4 text-sm text-slate-600 dark:bg-black/20 dark:text-slate-300">{item.note}</p>}</article><aside className="rounded-[1.5rem] bg-ink p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-mint">Mastery</p><div className="mt-4"><MasteryDots level={item.review_level} status={item.status}/></div><p className="mt-3 text-3xl font-semibold">Level {item.review_level}<span className="text-base text-slate-500"> / 5</span></p><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-400">Seen</dt><dd>{item.times_seen} times</dd></div><div className="flex justify-between"><dt className="text-slate-400">Next review</dt><dd>{item.status === "mastered" ? "Mastered" : date(`${item.next_review_at}T00:00:00`)}</dd></div></dl></aside></section>
    <section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/5"><h2 className="text-lg font-semibold">From your conversations <span className="ml-1 text-sm text-slate-400">{item.occurrences.length}</span></h2>{item.occurrences.length ? <div className="mt-4 space-y-3">{item.occurrences.map((occurrence) => <Link key={occurrence.sessions.id} to={`/sessions/${occurrence.sessions.id}`} className="block rounded-xl bg-mist p-4 transition hover:bg-mint/20 dark:bg-black/20"><div className="flex justify-between gap-3"><span className="text-sm font-semibold">{occurrence.sessions.topics.join(" · ")}</span><span className="text-xs text-slate-400">{date(`${occurrence.sessions.session_date}T00:00:00`)}</span></div>{occurrence.example_in_session && <p className="mt-2 text-sm italic text-slate-500">“{occurrence.example_in_session}”</p>}</Link>)}</div> : <p className="mt-3 text-sm text-slate-500">No linked sessions.</p>}</section>
    <section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/5"><h2 className="text-lg font-semibold">Review history <span className="ml-1 text-sm text-slate-400">{item.reviews.length}</span></h2>{item.reviews.length ? <div className="mt-4 space-y-4">{item.reviews.map((review) => <article key={review.id} className="border-b border-slate-100 pb-4 last:border-0 dark:border-white/10"><div className="flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${review.rating === "again" ? "bg-red-100 text-red-700" : review.rating === "hard" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{review.rating}</span><span className="text-xs text-slate-400">{review.channel} · {date(review.created_at)}</span></div><p className="mt-3 text-sm font-medium">{review.question}</p>{review.user_answer && <p className="mt-1 text-sm text-slate-500">Your answer: {review.user_answer}</p>}{review.evaluation && <p className="mt-2 text-sm text-emerald-700 dark:text-mint">{review.evaluation}</p>}</article>)}</div> : <p className="mt-3 text-sm text-slate-500">No reviews yet. This item will appear when it is due.</p>}</section>
  </div>;
}
